In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [5]:
data_diabetes = pd.read_csv('diabetes_prediction_dataset.csv')

In [6]:
data_diabetes.head()

gender   age  hypertension  heart_disease smoking_history    bmi  \
0  Female  80.0             0              1           never  25.19   
1  Female  54.0             0              0         No Info  27.32   
2    Male  28.0             0              0           never  27.32   
3  Female  36.0             0              0         current  23.45   
4    Male  76.0             1              1         current  20.14   

   HbA1c_level  blood_glucose_level  diabetes  
0          6.6                  140         0  
1          6.6                   80         0  
2          5.7                  158         0  
3          5.0                  155         0  
4          4.8                  155         0

In [7]:
data_diabetes['diabetes'].value_counts()

diabetes
0    91500
1     8500
Name: count, dtype: int64

In [8]:
X = data_diabetes.drop(columns = 'smoking_history', axis = 1)

In [9]:
X_data = X.drop(columns = 'gender', axis=1)

In [10]:
X_data

age  hypertension  heart_disease    bmi  HbA1c_level  \
0      80.0             0              1  25.19          6.6   
1      54.0             0              0  27.32          6.6   
2      28.0             0              0  27.32          5.7   
3      36.0             0              0  23.45          5.0   
4      76.0             1              1  20.14          4.8   
...     ...           ...            ...    ...          ...   
99995  80.0             0              0  27.32          6.2   
99996   2.0             0              0  17.37          6.5   
99997  66.0             0              0  27.83          5.7   
99998  24.0             0              0  35.42          4.0   
99999  57.0             0              0  22.43          6.6   

       blood_glucose_level  diabetes  
0                      140         0  
1                       80         0  
2                      158         0  
3                      155         0  
4                      155         0  
...                    ...       ...  
99995                   90         0  
99996                  100         0  
99997                  155         0  
99998                  100         0  
99999                   90         0  

[100000 rows x 7 columns]

In [11]:
X_data.groupby('diabetes').mean()

age  hypertension  heart_disease        bmi  HbA1c_level  \
diabetes                                                                   
0         40.115187      0.058984       0.029235  26.887163     5.396761   
1         60.946588      0.245647       0.149059  31.988382     6.934953   

          blood_glucose_level  
diabetes                       
0                  132.852470  
1                  194.094706

In [12]:
x = X_data.iloc[:,:-1].values

The colon (:) before the comma means "select all rows."
The :-1 part means "select all columns except the last one." It is using Python's slicing, where -1 refers to the last column, and :-1 excludes it.

In [13]:
x

array([[ 80.  ,   0.  ,   1.  ,  25.19,   6.6 , 140.  ],
       [ 54.  ,   0.  ,   0.  ,  27.32,   6.6 ,  80.  ],
       [ 28.  ,   0.  ,   0.  ,  27.32,   5.7 , 158.  ],
       ...,
       [ 66.  ,   0.  ,   0.  ,  27.83,   5.7 , 155.  ],
       [ 24.  ,   0.  ,   0.  ,  35.42,   4.  , 100.  ],
       [ 57.  ,   0.  ,   0.  ,  22.43,   6.6 ,  90.  ]])

In [14]:
y = X_data.iloc[:,6].values
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

.iloc[:, 6]: This is a way to select data using the .iloc indexer:

The colon (:) before the comma indicates that we're selecting all rows.
The number 6 after the comma refers to the column at index 6 (which is the 7th column since indexing starts from 0). This is where the labels or target values (Y) are located.

In [15]:
X_train,X_test,Y_train,Y_test = train_test_split(x,y, test_size=0.2, stratify=y, random_state=2)

In [16]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5)
classifier.fit(X_train, Y_train)

KNeighborsClassifier()

In [18]:
y_pred = classifier.predict(X_test)

In [19]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score
print(classification_report(Y_test, y_pred))
print(confusion_matrix(Y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98     18300
           1       0.90      0.69      0.78      1700

    accuracy                           0.97     20000
   macro avg       0.94      0.84      0.88     20000
weighted avg       0.97      0.97      0.97     20000

[[18173   127]
 [  530  1170]]


In [20]:
print("KNN Accuracy:", accuracy_score(Y_test, y_pred))

KNN Accuracy: 0.96715


In [21]:
input_data = (47.0,0,0,38.04,9.0,155) 
input_data_as_numpy_array = np.asarray(input_data)
#reshape the numpy array
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
#standardize the input data
std_data = scaler.transform(input_data_reshaped)
print(std_data)

[[ 0.2282115  -0.28523451 -0.2017537   1.61604094  3.23580744  0.418857  ]]


In [22]:
prediction_Knn = classifier.predict(std_data)
print(prediction_Knn)
if prediction_Knn == 1:
    print('diabetic')
else :
    print('non diabetic')

[1]
diabetic
